### ISSUE TITLE
Error creating channel group: could not create orderer group: cannot marshal metadata for orderer type etcdraft: cannot load client cert for consenter orderer1.example.com:7050: open server.crt: no such file or directory

### ISSUE THREAD

**Issue by agustinustheo** [Altoros/Ansible-Fabric-Starter#23]
When launching Fabric, I found an error when generating the ordered genesis block during the step `Generating orderer genesis block with configtxgen`.

I got this in return:

```
{
  "changed": true,
  "msg": "non-zero return code",
  "rc": 2,
  "stderr": "Connection to 10.0.3.38 closed.\r\n",
  "stderr_lines": [
    "Connection to 10.0.3.38 closed."
  ],
  "stdout": "\u001b[33m2022-09-28 17:11:30.421 UTC [common.tools.configtxgen] main -> WARN 001\u001b[0m Omitting the channel ID for configtxgen for output operations is deprecated.  Explicitly passing the channel ID will be required in the future, defaulting to 'testchainid'.\r\n\u001b[34m2022-09-28 17:11:30.422 UTC [common.tools.configtxgen] main -> INFO 002\u001b[0m Loading configuration\r\n\u001b[34m2022-09-28 17:11:30.436 UTC [common.tools.configtxgen.localconfig] completeInitialization -> INFO 003\u001b[0m orderer type: etcdraft\r\n\u001b[34m2022-09-28 17:11:30.436 UTC [common.tools.configtxgen.localconfig] completeInitialization -> INFO 004\u001b[0m Orderer.EtcdRaft.Options unset, setting to tick_interval:\"500ms\" election_tick:10 heartbeat_tick:1 max_inflight_blocks:5 snapshot_interval_size:20971520 \r\n\u001b[34m2022-09-28 17:11:30.436 UTC [common.tools.configtxgen.localconfig] Load -> INFO 005\u001b[0m Loaded configuration: /etc/hyperledger/artifacts/configtx.yaml\r\n\u001b[34m2022-09-28 17:11:30.459 UTC [common.tools.configtxgen.localconfig] completeInitialization -> INFO 006\u001b[0m orderer type: solo\r\n\u001b[34m2022-09-28 17:11:30.459 UTC [common.tools.configtxgen.localconfig] LoadTopLevel -> INFO 007\u001b[0m Loaded configuration: /etc/hyperledger/artifacts/configtx.yaml\r\n\u001b[35m2022-09-28 17:11:30.459 UTC [common.tools.configtxgen.encoder] New -> PANI 008\u001b[0m Error creating channel group: could not create orderer group: cannot marshal metadata for orderer type etcdraft: cannot load client cert for consenter orderer1.example.com:7050: open /etc/hyperledger/artifacts/crypto-config/ordererOrganizations/example.com/orderers/orderer1.example.com/tls/server.crt: no such file or directory\r\n\u001b[35m2022-09-28 17:11:30.459 UTC [common.tools.configtxgen] func1 -> PANI 009\u001b[0m Error creating channel group: could not create orderer group: cannot marshal metadata for orderer type etcdraft: cannot load client cert for consenter orderer1.example.com:7050: open /etc/hyperledger/artifacts/crypto-config/ordererOrganizations/example.com/orderers/orderer1.example.com/tls/server.crt: no such file or directory\r\npanic: Error creating channel group: could not create orderer group: cannot marshal metadata for orderer type etcdraft: cannot load client cert for consenter orderer1.example.com:7050: open /etc/hyperledger/artifacts/crypto-config/ordererOrganizations/example.com/orderers/orderer1.example.com/tls/server.crt: no such file or directory [recovered]\r\n\tpanic: Error creating channel group: could not create orderer group: cannot marshal metadata for orderer type etcdraft: cannot load client cert for consenter orderer1.example.com:7050: open /etc/hyperledger/artifacts/crypto-config/ordererOrganizations/example.com/orderers/orderer1.example.com/tls/server.crt: no such file or directory\r\n\r\ngoroutine 1 [running]:\r\ngithub.com/hyperledger/fabric/vendor/go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc00001e210, 0x0, 0x0, 0x0)\r\n\t/opt/gopath/src/github.com/hyperledger/fabric/vendor/go.uber.org/zap/zapcore/entry.go:229 +0x546\r\ngithub.com/hyperledger/fabric/vendor/go.uber.org/zap.(*SugaredLogger).log(0xc0000b8220, 0x4, 0xc0000c29a0, 0x148, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)\r\n\t/opt/gopath/src/github.com/hyperledger/fabric/vendor/go.uber.org/zap/sugar.go:234 +0x101\r\ngithub.com/hyperledger/fabric/vendor/go.uber.org/zap.(*SugaredLogger).Panicf(...)\r\n\t/opt/gopath/src/github.com/hyperledger/fabric/vendor/go.uber.org/zap/sugar.go:159\r\ngithub.com/hyperledger/fabric/common/flogging.(*FabricLogger).Panic(0xc0000b8228, 0xc000487a30, 0x1, 0x1)\r\n\t/opt/gopath/src/github.com/hyperledger/fabric/common/flogging/zap.go:73 +0x9a\r\nmain.main.func1()\r\n\t/opt/gopath/src/github.com/hyperledger/fabric/common/tools/configtxgen/main.go:260 +0x178\r\npanic(0xde3fc0, 0xc0003a4fd0)\r\n\t/opt/go/src/runtime/panic.go:522 +0x1b5\r\ngithub.com/hyperledger/fabric/vendor/go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc00001e210, 0x0, 0x0, 0x0)\r\n\t/opt/gopath/src/github.com/hyperledger/fabric/vendor/go.uber.org/zap/zapcore/entry.go:229 +0x546\r\ngithub.com/hyperledger/fabric/vendor/go.uber.org/zap.(*SugaredLogger).log(0xc0000b8210, 0x4, 0xf13059, 0x20, 0xc000487d70, 0x1, 0x1, 0x0, 0x0, 0x0)\r\n\t/opt/gopath/src/github.com/hyperledger/fabric/vendor/go.uber.org/zap/sugar.go:234 +0x101\r\ngithub.com/hyperledger/fabric/vendor/go.uber.org/zap.(*SugaredLogger).Panicf(...)\r\n\t/opt/gopath/src/github.com/hyperledger/fabric/vendor/go.uber.org/zap/sugar.go:159\r\ngithub.com/hyperledger/fabric/common/flogging.(*FabricLogger).Panicf(...)\r\n\t/opt/gopath/src/github.com/hyperledger/fabric/common/flogging/zap.go:74\r\ngithub.com/hyperledger/fabric/common/tools/configtxgen/encoder.New(0xc00007c580, 0xc0000b8208)\r\n\t/opt/gopath/src/github.com/hyperledger/fabric/common/tools/configtxgen/encoder/encoder.go:569 +0xb9\r\nmain.doOutputBlock(0xc00007c580, 0xf04907, 0xb, 0x7fff7dc2fc7e, 0x17, 0xc00007c580, 0x1)\r\n\t/opt/gopath/src/github.com/hyperledger/fabric/common/tools/configtxgen/main.go:34 +0x40\r\nmain.main()\r\n\t/opt/gopath/src/github.com/hyperledger/fabric/common/tools/configtxgen/main.go:294 +0xe61\r\n",
  "stdout_lines": [
    "\u001b[33m2022-09-28 17:11:30.421 UTC [common.tools.configtxgen] main -> WARN 001\u001b[0m Omitting the channel ID for configtxgen for output operations is deprecated.  Explicitly passing the channel ID will be required in the future, defaulting to 'testchainid'.",
    "\u001b[34m2022-09-28 17:11:30.422 UTC [common.tools.configtxgen] main -> INFO 002\u001b[0m Loading configuration",
    "\u001b[34m2022-09-28 17:11:30.436 UTC [common.tools.configtxgen.localconfig] completeInitialization -> INFO 003\u001b[0m orderer type: etcdraft",
    "\u001b[34m2022-09-28 17:11:30.436 UTC [common.tools.configtxgen.localconfig] completeInitialization -> INFO 004\u001b[0m Orderer.EtcdRaft.Options unset, setting to tick_interval:\"500ms\" election_tick:10 heartbeat_tick:1 max_inflight_blocks:5 snapshot_interval_size:20971520 ",
    "\u001b[34m2022-09-28 17:11:30.436 UTC [common.tools.configtxgen.localconfig] Load -> INFO 005\u001b[0m Loaded configuration: /etc/hyperledger/artifacts/configtx.yaml",
    "\u001b[34m2022-09-28 17:11:30.459 UTC [common.tools.configtxgen.localconfig] completeInitialization -> INFO 006\u001b[0m orderer type: solo",
    "\u001b[34m2022-09-28 17:11:30.459 UTC [common.tools.configtxgen.localconfig] LoadTopLevel -> INFO 007\u001b[0m Loaded configuration: /etc/hyperledger/artifacts/configtx.yaml",
    "\u001b[35m2022-09-28 17:11:30.459 UTC [common.tools.configtxgen.encoder] New -> PANI 008\u001b[0m Error creating channel group: could not create orderer group: cannot marshal metadata for orderer type etcdraft: cannot load client cert for consenter orderer1.example.com:7050: open /etc/hyperledger/artifacts/crypto-config/ordererOrganizations/example.com/orderers/orderer1.example.com/tls/server.crt: no such file or directory",
    "\u001b[35m2022-09-28 17:11:30.459 UTC [common.tools.configtxgen] func1 -> PANI 009\u001b[0m Error creating channel group: could not create orderer group: cannot marshal metadata for orderer type etcdraft: cannot load client cert for consenter orderer1.example.com:7050: open /etc/hyperledger/artifacts/crypto-config/ordererOrganizations/example.com/orderers/orderer1.example.com/tls/server.crt: no such file or directory",
    "panic: Error creating channel group: could not create orderer group: cannot marshal metadata for orderer type etcdraft: cannot load client cert for consenter orderer1.example.com:7050: open /etc/hyperledger/artifacts/crypto-config/ordererOrganizations/example.com/orderers/orderer1.example.com/tls/server.crt: no such file or directory [recovered]",
    "\tpanic: Error creating channel group: could not create orderer group: cannot marshal metadata for orderer type etcdraft: cannot load client cert for consenter orderer1.example.com:7050: open /etc/hyperledger/artifacts/crypto-config/ordererOrganizations/example.com/orderers/orderer1.example.com/tls/server.crt: no such file or directory",
    "",
    "goroutine 1 [running]:",
    "github.com/hyperledger/fabric/vendor/go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc00001e210, 0x0, 0x0, 0x0)",
    "\t/opt/gopath/src/github.com/hyperledger/fabric/vendor/go.uber.org/zap/zapcore/entry.go:229 +0x546",
    "github.com/hyperledger/fabric/vendor/go.uber.org/zap.(*SugaredLogger).log(0xc0000b8220, 0x4, 0xc0000c29a0, 0x148, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)",
    "\t/opt/gopath/src/github.com/hyperledger/fabric/vendor/go.uber.org/zap/sugar.go:234 +0x101",
    "github.com/hyperledger/fabric/vendor/go.uber.org/zap.(*SugaredLogger).Panicf(...)",
    "\t/opt/gopath/src/github.com/hyperledger/fabric/vendor/go.uber.org/zap/sugar.go:159",
    "github.com/hyperledger/fabric/common/flogging.(*FabricLogger).Panic(0xc0000b8228, 0xc000487a30, 0x1, 0x1)",
    "\t/opt/gopath/src/github.com/hyperledger/fabric/common/flogging/zap.go:73 +0x9a",
    "main.main.func1()",
    "\t/opt/gopath/src/github.com/hyperledger/fabric/common/tools/configtxgen/main.go:260 +0x178",
    "panic(0xde3fc0, 0xc0003a4fd0)",
    "\t/opt/go/src/runtime/panic.go:522 +0x1b5",
    "github.com/hyperledger/fabric/vendor/go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc00001e210, 0x0, 0x0, 0x0)",
    "\t/opt/gopath/src/github.com/hyperledger/fabric/vendor/go.uber.org/zap/zapcore/entry.go:229 +0x546",
    "github.com/hyperledger/fabric/vendor/go.uber.org/zap.(*SugaredLogger).log(0xc0000b8210, 0x4, 0xf13059, 0x20, 0xc000487d70, 0x1, 0x1, 0x0, 0x0, 0x0)",
    "\t/opt/gopath/src/github.com/hyperledger/fabric/vendor/go.uber.org/zap/sugar.go:234 +0x101",
    "github.com/hyperledger/fabric/vendor/go.uber.org/zap.(*SugaredLogger).Panicf(...)",
    "\t/opt/gopath/src/github.com/hyperledger/fabric/vendor/go.uber.org/zap/sugar.go:159",
    "github.com/hyperledger/fabric/common/flogging.(*FabricLogger).Panicf(...)",
    "\t/opt/gopath/src/github.com/hyperledger/fabric/common/flogging/zap.go:74",
    "github.com/hyperledger/fabric/common/tools/configtxgen/encoder.New(0xc00007c580, 0xc0000b8208)",
    "\t/opt/gopath/src/github.com/hyperledger/fabric/common/tools/configtxgen/encoder/encoder.go:569 +0xb9",
    "main.doOutputBlock(0xc00007c580, 0xf04907, 0xb, 0x7fff7dc2fc7e, 0x17, 0xc00007c580, 0x1)",
    "\t/opt/gopath/src/github.com/hyperledger/fabric/common/tools/configtxgen/main.go:34 +0x40",
    "main.main()",
    "\t/opt/gopath/src/github.com/hyperledger/fabric/common/tools/configtxgen/main.go:294 +0xe61"
  ]
}
```

**Comment by agustinustheo** [comment]
For future references, I found the error and it turns out it's because I edited the `hosts_raft.yaml` file and changed the `orderer_count` to 1 instead of 4. 

The certificates were generated for only 1 orderer which is false, so I reverted the change back to 4 and it was all fixed.
